# Generated by Django 5.2.17 on 2026-10-01 19:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=60)),
                ('offered_skill', models.CharField(choices=[('design', 'Design'), ('photography', 'Photography'), ('coding', 'Coding'), ('writing', 'Writing'), ('presentations', 'Presentations'), ('other', 'Other')], max_length=32)),
                ('offer_description', models.CharField(max_length=500)),
                ('wanted_help', models.CharField(max_length=500)),
                ('availability', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(editable=False)),
                ('expires_at', models.DateTimeField(editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'offered_skill', 'created_at'], name='listing_status_skill_created')],
            },
        ),
    ]
