# Generated by Django 5.2.17 on 2026-10-01 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='display_name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='offer_description',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='wanted_help',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
